# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 09:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_file', '0005_auto_20160713_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerfile',
            name='file',
            field=filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.PROTECT, to='filer.File', verbose_name='file'),
        ),
    ]
