# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_image', '0009_auto_20160713_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerimage',
            name='file_link',
            field=filer.fields.file.FilerFileField(blank=True, default=None, help_text='if present image will be clickable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='filer.File', verbose_name='file link'),
        ),
        migrations.AlterField(
            model_name='filerimage',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.FILER_IMAGE_MODEL, verbose_name='image'),
        ),
    ]
