# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 09:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_filer_link', '0007_auto_20160713_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerlinkplugin',
            name='file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filer.File'),
        ),
    ]
